name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - "27.1"
          - "27.2"
          - "28.2"
          - "29.4"
          - "snapshot"

    steps:
      - uses: actions/checkout@v6

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Run tests
        run: make test

      - name: Byte-compile
        run: make compile

      - name: Check Formatting
        if: matrix.emacs_version == 'snapshot'
        run: make format-check

      - name: Checkdoc
        run: make checkdoc

      - name: Lint
        run: make lint
