name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - "27.1"
          - "27.2"
          - "28.2"
          - "29.4"
          - "snapshot"

    steps:
      - uses: actions/checkout@v6

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Run tests
        run: make test

      - name: Byte-compile
        run: make compile

      - name: Check Formatting
        if: matrix.emacs_version == '29.4'
        run: make format-check

      - name: Lint
        run: |
          emacs -batch --eval "(require 'package)" --eval "(add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\") t)" --eval "(package-initialize)" --eval "(package-refresh-contents)" --eval "(package-install 'package-lint)"
          emacs -batch -L . --eval "(require 'package-lint)" -f package-lint-batch-and-exit *.el
